var Deck = require('card-deck');

cards = [
    { suit: 'Spades', rank: 'A'},
    { suit: 'Spades', rank: '2'},
    { suit: 'Spades', rank: '3'},
    { suit: 'Spades', rank: '4'},
    { suit: 'Spades', rank: '5'},
    { suit: 'Spades', rank: '6'},
    { suit: 'Spades', rank: '7'},
    { suit: 'Spades', rank: '8'},
    { suit: 'Spades', rank: '9'},
    { suit: 'Spades', rank: '10'},
    { suit: 'Spades', rank: 'J'},
    { suit: 'Spades', rank: 'Q'},
    { suit: 'Spades', rank: 'K'},
  
    { suit: 'Hearts', rank: 'A'},
    { suit: 'Hearts', rank: '2'},
    { suit: 'Hearts', rank: '3'},
    { suit: 'Hearts', rank: '4'},
    { suit: 'Hearts', rank: '5'},
    { suit: 'Hearts', rank: '6'},
    { suit: 'Hearts', rank: '7'},
    { suit: 'Hearts', rank: '8'},
    { suit: 'Hearts', rank: '9'},
    { suit: 'Hearts', rank: '10'},
    { suit: 'Hearts', rank: 'J'},
    { suit: 'Hearts', rank: 'Q'},
    { suit: 'Hearts', rank: 'K'},
  
    { suit: 'Diamonds', rank: 'A'},
    { suit: 'Diamonds', rank: '2'},
    { suit: 'Diamonds', rank: '3'},
    { suit: 'Diamonds', rank: '4'},
    { suit: 'Diamonds', rank: '5'},
    { suit: 'Diamonds', rank: '6'},
    { suit: 'Diamonds', rank: '7'},
    { suit: 'Diamonds', rank: '8'},
    { suit: 'Diamonds', rank: '9'},
    { suit: 'Diamonds', rank: '10'},
    { suit: 'Diamonds', rank: 'J'},
    { suit: 'Diamonds', rank: 'Q'},
    { suit: 'Diamonds', rank: 'K'},
  
    { suit: 'Clubs', rank: 'A'},
    { suit: 'Clubs', rank: '2'},
    { suit: 'Clubs', rank: '3'},
    { suit: 'Clubs', rank: '4'},
    { suit: 'Clubs', rank: '5'},
    { suit: 'Clubs', rank: '6'},
    { suit: 'Clubs', rank: '7'},
    { suit: 'Clubs', rank: '8'},
    { suit: 'Clubs', rank: '9'},
    { suit: 'Clubs', rank: '10'},
    { suit: 'Clubs', rank: 'J'},
    { suit: 'Clubs', rank: 'Q'},
    { suit: 'Clubs', rank: 'K'},
  ];
  var StandardDeck = new Deck(cards);
  
  module.exports = StandardDeck;